commands:
  # ------------------------------------------------
  #
  # GLOBAL COMMANDS
  #
  # SET TO true TO PUSH ALL COMMANDS GLOBALLY
  #
  # ------------------------------------------------
  global: false

  # ------------------------------------------------
  #
  # GUILD COMMANDS
  #
  # LIST ALL GUILD IDS YOU WANT THE COMMANDS TO BE PUSHED TO
  # OR PUSH TO ALL GUILDS WITH allGuilds = true
  #
  # ------------------------------------------------
  guilds:
  - "757263832761630790"
  allGuilds: false